### ISSUE TITLE
KF5: Crashes Baloo continuously if assertions are enabled

### ISSUE THREAD

**Issue by Tatsh** [GerbilSoft/rom-properties#410]
```c++
#9  0x00007f5364a5dd66 in LibRomData::ColecoVision::isRomSupported_static (info=<optimized out>)
    at /var/tmp/portage/x11-misc/rom-properties-2.3/work/rom-properties-2.3/src/libromdata/Console/ColecoVision.cpp:343
#10 0x00007f5364a58adc in LibRomData::RomDataFactory::create (
    file=std::shared_ptr<LibRpFile::IRpFile> (use count 2, weak count 0) = {...}, attrs=<optimized out>)
    at /var/tmp/portage/x11-misc/rom-properties-2.3/work/rom-properties-2.3/src/libromdata/RomDataFactory.cpp:958
#11 0x00007f5365eba295 in RomPropertiesKF5::ExtractorPlugin::extract (this=<optimized out>, result=0x7ffd53e9d510)
    at /var/tmp/portage/x11-misc/rom-properties-2.3/work/rom-properties-2.3/src/kde/plugins/ExtractorPlugin.cpp:227
#12 0x00005570f5b24e28 in Baloo::App::index (this=this@entry=0x7ffd53e9dbc0, tr=0x5570f6cc2550, url=...,
    id=id@entry=38497523897089630)
```

https://github.com/GerbilSoft/rom-properties/blob/v2.3/src/libromdata/Console/ColecoVision.cpp#L342

Can assertions be disabled while still building with `RelWithDebInfo`?

**Comment by qookei** [comment]
AFAICS the failing assert was removed in this commit: https://github.com/GerbilSoft/rom-properties/commit/e1a6e6b467b87c330595e175cbb8f9b64c617052, which hasn't made it into a release yet.

**Comment by GerbilSoft** [comment]
This particular issue was fixed by getting rid of that assertion. I'll take a look at properly implementing RelWithDebInfo later this week. (I haven't really used this configuration much myself; just Debug and Release.)
